// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: time_page_token.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimePageToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdatedAt int64  `protobuf:"varint,1,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PageSize  uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Id        uint64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TimePageToken) Reset() {
	*x = TimePageToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_time_page_token_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimePageToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimePageToken) ProtoMessage() {}

func (x *TimePageToken) ProtoReflect() protoreflect.Message {
	mi := &file_time_page_token_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimePageToken.ProtoReflect.Descriptor instead.
func (*TimePageToken) Descriptor() ([]byte, []int) {
	return file_time_page_token_proto_rawDescGZIP(), []int{0}
}

func (x *TimePageToken) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *TimePageToken) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *TimePageToken) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_time_page_token_proto protoreflect.FileDescriptor

var file_time_page_token_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x0d, 0x54, 0x69, 0x6d, 0x65, 0x50,
	0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x42, 0x3c, 0x42, 0x12, 0x54, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x67, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x24, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x70,
	0x68, 0x69, 0x6c, 0x65, 0x2f, 0x6c, 0x69, 0x6c, 0x6c, 0x65, 0x79, 0x67, 0x72, 0x61, 0x6d, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_time_page_token_proto_rawDescOnce sync.Once
	file_time_page_token_proto_rawDescData = file_time_page_token_proto_rawDesc
)

func file_time_page_token_proto_rawDescGZIP() []byte {
	file_time_page_token_proto_rawDescOnce.Do(func() {
		file_time_page_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_time_page_token_proto_rawDescData)
	})
	return file_time_page_token_proto_rawDescData
}

var file_time_page_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_time_page_token_proto_goTypes = []interface{}{
	(*TimePageToken)(nil), // 0: TimePageToken
}
var file_time_page_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_time_page_token_proto_init() }
func file_time_page_token_proto_init() {
	if File_time_page_token_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_time_page_token_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimePageToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_time_page_token_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_time_page_token_proto_goTypes,
		DependencyIndexes: file_time_page_token_proto_depIdxs,
		MessageInfos:      file_time_page_token_proto_msgTypes,
	}.Build()
	File_time_page_token_proto = out.File
	file_time_page_token_proto_rawDesc = nil
	file_time_page_token_proto_goTypes = nil
	file_time_page_token_proto_depIdxs = nil
}
